version: "3"
services:
  web:
    build: machine
    ports:
      - "80"
      - "65000"

    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0

    network_mode: "host"
    hostname: "rath-jp"

  alice:
    build: alice
    ports:
      - "55555:55555"
